### PR TITLE
Implement the rest of requirements for stocks for R1

### PR DESCRIPTION
**Pull request by mikairi**
For R1, the stocks page has the following requirements:
- Current price
- Day's high
- Day's low
- Yearly high
- Yearly low
- An interactive chart of the stock (not just a retrieved image)

They are now all implemented. You can see a preview on http://vm344f.se.rit.edu/app

I know you have been working on this @rayrobdod, but I don't know how far you are along regarding these requirements. We are really short on time, and we need these done in case we have to present on Monday.

### CODE REVIEW

**Comment by rayrobdod** [comment]
You're clearly farther ahead than I am.

**Comment by rayrobdod** [comment]
The search page throws up a stack trace for an invalid or unused ticker symbol in the query

**Comment by mikairi** [comment]
Yup it's a known bug. Just need to handle the exception from the Yahoo API somehow. But for our R1 demo purpose, it should be fine as long as we don't punch in incorrect symbols.

You can create an issue or I can do it later. Was too lazy to make one last night.

**Comment by rayrobdod** [comment]
It feels wrong to make an issue for code that hasn't been merged to master yet.

**Comment by mikairi** [comment]
You're right. In any case, we have a little more time so I will put in some exception handling to this merge.

**Comment by rayrobdod** [comment]
If the stock market hasn't opened yet today, then the day's high and low will be reported by Yahoo as `null`.

I considered saving this for a formal bug report, but our presentation will be before 9:30 Eastern.

**Comment by mikairi** [comment]
Are other params still returned? Damn it I don't actually know anything about how stocks work...

**Comment by rayrobdod** [comment]
# GetQuoteAsync
- For an unused ticker symbol: all values were null, but did exist.
- For a valid symbol Between 8AM and 930AM, Symbol, Ask, YearHigh and YearLow had values; DayHigh and DayLow. Did not note other symbols
- For a valid symbol between 930AM and midnight, all values existed and had values

I don't know what time zone Yahoo is in or when it changes from 'still today' to

# HistoricalData
- For invalid symbol: results is null. `null["quote"]; dereferencing a null pointer`
- For dates with no data: The console decided to die when I tried to check, but it might be worth looking into. Probably an empty list
- Else: as per normal case

# Other

There's always the chance for a 400, especially if someone sends anything containing an unescaped `"`.

**Comment by mikairi** [comment]
Thanks. So there just needs to be a few checks for null returned from Yahoo.

Dates with no data indeed return an empty list, but that should not happen within our code since we get a range of dates that cover at least a whole week. I'm considering raising it to a month. If a stock isn't listed at all in a month time it might as well not exist. :open_mouth: 

Nice catch on sanitization. I'm fairly certain an `HttpUtility.UrlEncode()` for the symbol arg should do the trick.

**Comment by mikairi** [comment]
Tests passed and the pages look decent enough. I think it's good to go.

**Comment by rayrobdod** [comment]
In the box-and-whisker plots, it took me a bit to realize that the white boxes indicate close > open and blue boxes indicate open > close.
The new chart is SVG. That I approve of.
I couldn't produce any problems via keyboard banging.
It looks good from my IE-biased perspective.

**Pull request merged**
