### PR TITLE
Html css skeleton

### PR DESCRIPTION
**Pull request by reaper10567**
Basic HTML is done, can be hooked up with existing functions. Will work more on stocks page later

### CODE REVIEW

**Comment by mikairi** [comment]
Can you remove all the unnecessary localizations for the calendar? If it's not too much work.

**Comment by rayrobdod** [comment]
The calendar's demos shouldn't be necessary either.

**Comment by reaper10567** [comment]
Not sure what you mean by the localizations,  but I can delete the demos.

**Comment by mikairi** [comment]
Basically the `/src/SE344/wwwroot/fullcalendar-2.4.0/lang` folder.

**Comment by reaper10567** [comment]
Ohhhhh. Okay.  I'll do that in a few minutes

**Comment by mikairi** [comment]
A better way of installing 3rd-party js libraries like this is to run `bower install fullcalendar --save` from the `src/SE344` folder. But doing it manually is fine too if you don't fully understand dependency management (Bower) and we're running short on time.

**Comment by reaper10567** [comment]
yeah, idk how to use bower atm. And the calendar isn't really part of R1 so we can worry about it another time

**Pull request merged**
